// Figma render template + builder. Pure module: produces the JS string that
// runs inside figma_execute. Not executable in Node — the Figma plugin API is
// only available at runtime in the Bridge plugin.
//
// Substitutions: __MANIFEST_JSON__ and __SELECTION_JSON__ are replaced via
// JSON.stringify; both are validated upstream so injection is impossible.

export class RenderJsError extends Error {
  constructor(message, { code = 'UNKNOWN' } = {}) {
    super(message)
    this.name = 'RenderJsError'
    this.code = code
  }
}

export const RENDER_TEMPLATE_JS = String.raw`
// ============================================================================
// Meet Criteria — render template (generated by lib/figma-render.mjs).
// Contract: lib/render-manifest.mjs builds the manifest; this template draws.
// Do not edit here — edit the template in lib/figma-render.mjs.
// ============================================================================
const MANIFEST = __MANIFEST_JSON__
const SELECTION = __SELECTION_JSON__

const FONT_FAMILY = (MANIFEST.tokens && MANIFEST.tokens['font.family.default']) || 'Inter'
const TEXT_PRIMARY = (MANIFEST.tokens && MANIFEST.tokens['text.primary']) || '#1d2b2c'
const CARD_BG     = (MANIFEST.tokens && MANIFEST.tokens['card.background']) || '#f5f8f8'
const BANNER_BG   = (MANIFEST.tokens && MANIFEST.tokens['banner.background']) || '#dee9e8'

function hexToRgb(hex) {
  const n = parseInt(String(hex).slice(1), 16)
  return { r: ((n >> 16) & 0xff) / 255, g: ((n >> 8) & 0xff) / 255, b: (n & 0xff) / 255 }
}

function solidFill(hex) {
  return { type: 'SOLID', color: hexToRgb(hex) }
}

function setPluginData(node, data) {
  if (!data) return
  for (const [k, v] of Object.entries(data)) {
    const value = (typeof v === 'object' && v !== null) ? JSON.stringify(v) : String(v)
    node.setSharedPluginData('meetCriteria', k, value)
  }
}

function makeText(characters, opts) {
  const t = figma.createText()
  t.fontName = { family: FONT_FAMILY, style: opts.style }
  t.fontSize = opts.size
  if (opts.lineHeight === 'AUTO') {
    t.lineHeight = { unit: 'AUTO' }
  } else if (typeof opts.lineHeight === 'number') {
    t.lineHeight = { unit: 'PERCENT', value: opts.lineHeight }
  }
  if (typeof opts.letterSpacingPercent === 'number') {
    t.letterSpacing = { unit: 'PERCENT', value: opts.letterSpacingPercent }
  }
  t.characters = characters
  t.fills = [solidFill(opts.color || TEXT_PRIMARY)]
  return t
}

function makeAutoFrame(name, kind, opts) {
  const f = figma.createFrame()
  f.name = name
  f.layoutMode = kind
  f.itemSpacing = opts.gap ?? 0
  f.paddingTop = opts.paddingTop ?? 0
  f.paddingRight = opts.paddingRight ?? 0
  f.paddingBottom = opts.paddingBottom ?? 0
  f.paddingLeft = opts.paddingLeft ?? 0
  f.cornerRadius = opts.corner ?? 0
  f.fills = opts.fillHex ? [solidFill(opts.fillHex)] : []
  f.strokes = []
  if (opts.counterAxisAlignItems) f.counterAxisAlignItems = opts.counterAxisAlignItems
  return f
}

function buildProblemStatementCard(node) {
  const f = makeAutoFrame('Problem statement', 'VERTICAL', {
    gap: 32, paddingTop: 48, paddingRight: 48, paddingBottom: 48, paddingLeft: 48,
    corner: 24, fillHex: CARD_BG,
  })
  f.x = node.x; f.y = node.y
  f.resize(node.width, node.height)
  f.primaryAxisSizingMode = 'FIXED'
  f.counterAxisSizingMode = 'FIXED'

  const heading = makeText(node.heading, { style: 'Medium', size: 48, lineHeight: 100, color: TEXT_PRIMARY })
  heading.layoutAlign = 'STRETCH'
  heading.textAutoResize = 'HEIGHT'
  f.appendChild(heading)

  const body = makeText(node.body, { style: 'Regular', size: 20, lineHeight: 120, color: TEXT_PRIMARY })
  body.layoutAlign = 'STRETCH'
  body.textAutoResize = 'HEIGHT'
  f.appendChild(body)

  setPluginData(f, node.pluginData)
  return f
}

function buildFlowNameBanner(banner, flowPluginData) {
  const f = makeAutoFrame('Flow Name — ' + banner.text, 'HORIZONTAL', {
    gap: 40, paddingTop: 56, paddingRight: 56, paddingBottom: 56, paddingLeft: 56,
    corner: 48, fillHex: BANNER_BG, counterAxisAlignItems: 'CENTER',
  })
  f.x = banner.x; f.y = banner.y
  f.resize(banner.width, banner.height)
  f.primaryAxisSizingMode = 'FIXED'
  f.counterAxisSizingMode = 'AUTO'

  const t = makeText(banner.text, { style: 'Medium', size: 80, lineHeight: 'AUTO', letterSpacingPercent: -4, color: TEXT_PRIMARY })
  t.layoutGrow = 1
  t.textAutoResize = 'TRUNCATE'
  t.textAlignVertical = 'CENTER'
  f.appendChild(t)

  setPluginData(f, flowPluginData)
  return f
}

function buildScreenNameTag(tag, screenPluginData) {
  const f = makeAutoFrame('Screen Name — ' + tag.text, 'HORIZONTAL', {
    gap: 16, paddingTop: 24, paddingRight: 20, paddingBottom: 24, paddingLeft: 20,
    corner: 16, fillHex: CARD_BG, counterAxisAlignItems: 'CENTER',
  })
  f.x = tag.x; f.y = tag.y
  f.resize(tag.width, tag.height)
  f.primaryAxisSizingMode = 'FIXED'
  f.counterAxisSizingMode = 'AUTO'

  const t = makeText(tag.text, { style: 'Medium', size: 28, lineHeight: 'AUTO', letterSpacingPercent: -2, color: TEXT_PRIMARY })
  t.textAutoResize = 'WIDTH_AND_HEIGHT'
  f.appendChild(t)

  setPluginData(f, screenPluginData)
  return f
}

async function buildIPhonePlaceholder(placeholder, figId, indexLabel) {
  const f = figma.createFrame()
  f.name = 'iPhone 13 & 14 - ' + indexLabel
  f.layoutMode = 'NONE'
  f.cornerRadius = 16
  f.fills = [solidFill(CARD_BG)]
  f.strokes = []
  f.x = placeholder.x; f.y = placeholder.y
  f.resize(placeholder.width, placeholder.height)

  if (figId) {
    const original = await figma.getNodeByIdAsync(figId)
    if (original && typeof original.clone === 'function') {
      const dup = original.clone()
      dup.x = 0; dup.y = 0
      f.appendChild(dup)
    }
  }
  return f
}

function buildAnalysisOverviewCard(node) {
  const f = makeAutoFrame('Analysis Overview', 'VERTICAL', {
    gap: 48, paddingTop: 48, paddingRight: 48, paddingBottom: 48, paddingLeft: 48,
    corner: 24, fillHex: CARD_BG,
  })
  f.x = node.x; f.y = node.y
  f.resize(node.width, node.height)
  f.primaryAxisSizingMode = 'FIXED'
  f.counterAxisSizingMode = 'FIXED'

  const heading = makeText(node.heading, { style: 'Medium', size: 48, lineHeight: 100, color: TEXT_PRIMARY })
  heading.layoutAlign = 'STRETCH'
  heading.textAutoResize = 'HEIGHT'
  f.appendChild(heading)

  for (const sec of (node.sections || [])) {
    const sub = makeAutoFrame('Section — ' + sec.key, 'VERTICAL', { gap: 20 })
    sub.layoutAlign = 'STRETCH'
    sub.layoutSizingHorizontal = undefined
    sub.primaryAxisSizingMode = 'AUTO'
    sub.counterAxisSizingMode = 'FIXED'

    const subHeading = makeText(sec.heading, { style: 'Semi Bold', size: 28, lineHeight: 100, color: TEXT_PRIMARY })
    subHeading.layoutAlign = 'STRETCH'
    subHeading.textAutoResize = 'HEIGHT'
    sub.appendChild(subHeading)

    const subBody = makeText(sec.body || '', { style: 'Regular', size: 20, lineHeight: 120, color: TEXT_PRIMARY })
    subBody.layoutAlign = 'STRETCH'
    subBody.textAutoResize = 'HEIGHT'
    sub.appendChild(subBody)

    f.appendChild(sub)
  }

  setPluginData(f, node.pluginData)
  return f
}

// ----- main flow -----
await figma.loadFontAsync({ family: FONT_FAMILY, style: 'Regular' })
await figma.loadFontAsync({ family: FONT_FAMILY, style: 'Medium' })
await figma.loadFontAsync({ family: FONT_FAMILY, style: 'Semi Bold' })
await figma.loadAllPagesAsync()

// Always create a dedicated page so the user's reference page is left untouched.
const existingPage = figma.root.children.find((p) => p.name === MANIFEST.page.name)
if (existingPage) {
  return JSON.stringify({ error: 'Page "' + MANIFEST.page.name + '" already exists. Rename or delete it first.' })
}

const page = figma.createPage()
page.name = MANIFEST.page.name
await figma.setCurrentPageAsync(page)

const section = figma.createSection()
section.name = MANIFEST.section.name
section.fills = [solidFill(MANIFEST.layout.background)]
section.resizeWithoutConstraints(MANIFEST.section.width, MANIFEST.section.height)
section.x = 0
section.y = 0
page.appendChild(section)
setPluginData(section, MANIFEST.section.pluginData)

// Render nodes (positions are absolute inside the section).
let placeholderIndex = 0
for (const node of MANIFEST.nodes) {
  if (node.component === 'ProblemStatement') {
    section.appendChild(buildProblemStatementCard(node))
  } else if (node.component === 'AnalysisOverview') {
    section.appendChild(buildAnalysisOverviewCard(node))
  } else if (node.component === 'FlowList') {
    let selectionIdx = 0
    for (const flow of node.children) {
      section.appendChild(buildFlowNameBanner(flow.banner, flow.pluginData))
      for (const screen of flow.screens) {
        section.appendChild(buildScreenNameTag(screen.tag, screen.pluginData))
        const figId = SELECTION[selectionIdx++]
        placeholderIndex++
        section.appendChild(await buildIPhonePlaceholder(screen.placeholder, figId, String(placeholderIndex)))
      }
    }
  }
}

return JSON.stringify({
  page: page.id,
  section: section.id,
  name: section.name,
})
`

function expectedSelectionLength(manifest) {
  if (!Array.isArray(manifest.nodes)) {
    throw new RenderJsError('manifest.nodes must be an array', { code: 'INVALID_MANIFEST' })
  }
  if (manifest.type !== 'feature') return 0
  const flows = manifest.nodes.find((n) => n.id === 'flows')
  if (!flows || !Array.isArray(flows.children)) {
    throw new RenderJsError('feature manifest is missing the "flows" node', { code: 'INVALID_MANIFEST' })
  }
  return flows.children.reduce((acc, f) => acc + (Array.isArray(f.screens) ? f.screens.length : 0), 0)
}

export function buildRenderJs({ manifest, selectionIds }) {
  if (!manifest || typeof manifest !== 'object') {
    throw new RenderJsError('manifest is required', { code: 'MISSING_MANIFEST' })
  }
  if (!Array.isArray(selectionIds)) {
    throw new RenderJsError('selectionIds must be an array', { code: 'INVALID_SELECTION_TYPE' })
  }
  const expected = expectedSelectionLength(manifest)
  if (selectionIds.length !== expected) {
    throw new RenderJsError(
      `selectionIds has ${selectionIds.length} item(s); manifest expects ${expected}.`,
      { code: 'SELECTION_LENGTH_MISMATCH' },
    )
  }
  return RENDER_TEMPLATE_JS
    .replace(/__MANIFEST_JSON__/g, JSON.stringify(manifest))
    .replace(/__SELECTION_JSON__/g, JSON.stringify(selectionIds))
}
